databases:
  - name: searchbox
    databaseName: searchbox_mjph
    user: searchbox_mjph_user

services:
  - type: web
    name: search_analytics
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: searchbox
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false